version: "3.5"

services:
  fabio:
    image: fabiolb/fabio
    container_name: fabio
    environment:
    - FABIO_REGISTRY_CONSUL_ADDR=consul:8500
    networks:
      - dshop
    ports:
    - '9998:9998'
    - '9999:9999'

networks:
  dshop:
    name: dshop-network
    external: true