version: "3.5"

services:
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - '8086:8086'
    networks:
      - dshop
    volumes:
      - '/tmp/influxdb:/var/lib/influxdb'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    networks:
      - dshop
    volumes:
      - '/tmp/grafana:/var/lib/grafana'

networks:
  dshop:
    name: dshop-network
    external: true