version: "3.5"

services:
  mongo:
    image: mongo:4
    container_name: mongo
    ports:
      - '27017:27017'
    networks:
      - dshop
    volumes:
      - './mongo:/data/db'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - dshop
    volumes: 
      - /tmp/rabbitmq:/var/lib/rabbitmq'

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - dshop
    volumes: 
      - '/tmp/redis/:/data'

networks:
  dshop:
    name: dshop-network